sonar.projectKey=ember-brand-manager
sonar.host.url=https://sonarqube.upfluence.co
sonar.organization=upfluence
sonar.sources=packages/ember-brand-manager/addon/,packages/ember-brand-manager/app/
sonar.javascript.lcov.reportPaths=./packages/ember-brand-manager/coverage/lcov.info
sonar.typescript.tsconfigPaths=./packages/ember-brand-manager/tsconfig.json
sonar.coverage.exclusions=packages/ember-brand-manager/app/
sonar.cpd.exclusions=packages/ember-brand-manager/tests/,**/tests/**,*-test.js,*-test.ts,test-support/
sonar.tests=packages/ember-brand-manager/tests/
sonar.html.file.suffixes=.hbs
