---
name: CI
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_VERSION: '14'

jobs:
  release:
    name: Release Package
    runs-on: ubuntu-20.04
    if: contains(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: '${{ env.NODE_VERSION }}'
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      - name: Publish
        run: |
          echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" >> ~/.npmrc
          npm publish --access public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
